sudo: true
language: node_js
before_install:
- chmod -R +x scripts
install:
- "./scripts/install.sh"
- "./scripts/config.sh"
deploy:
  provider: script
  skip_cleanup: true
  script: "./buildScripts/deployDevelopment.sh"
  on:
    branch: master
